"use client"

import { useState } from "react"
import {
  FileText,
  FileSpreadsheet,
  FileImage,
  FileCode,
  Download,
  Trash2,
  Eye,
  Search,
  Grid,
  List,
  MoreVertical,
  Bot,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu"
import { cn } from "@/lib/utils"

interface GeneratedFile {
  id: string
  name: string
  type: "csv" | "json" | "png" | "py" | "txt"
  size: string
  createdAt: string
  generatedBy: string
}

const initialFiles: GeneratedFile[] = [
  {
    id: "1",
    name: "cleaned_sales_data.csv",
    type: "csv",
    size: "2.4 MB",
    createdAt: "2024-01-15 14:30",
    generatedBy: "Data Cleaning Agent",
  },
  {
    id: "2",
    name: "analysis_report.json",
    type: "json",
    size: "156 KB",
    createdAt: "2024-01-15 15:45",
    generatedBy: "AI Agent",
  },
  {
    id: "3",
    name: "revenue_chart.png",
    type: "png",
    size: "890 KB",
    createdAt: "2024-01-14 10:20",
    generatedBy: "Visualization Agent",
  },
  {
    id: "4",
    name: "feature_engineering.py",
    type: "py",
    size: "12 KB",
    createdAt: "2024-01-14 09:15",
    generatedBy: "AI Agent",
  },
  {
    id: "5",
    name: "outlier_detection_results.csv",
    type: "csv",
    size: "1.1 MB",
    createdAt: "2024-01-13 16:00",
    generatedBy: "Outlier Detection Agent",
  },
  {
    id: "6",
    name: "insights_summary.txt",
    type: "txt",
    size: "24 KB",
    createdAt: "2024-01-13 11:30",
    generatedBy: "AI Agent",
  },
]

const getFileIcon = (type: string) => {
  switch (type) {
    case "csv":
      return FileSpreadsheet
    case "json":
      return FileCode
    case "png":
      return FileImage
    case "py":
      return FileCode
    default:
      return FileText
  }
}

const getFileColor = (type: string) => {
  switch (type) {
    case "csv":
      return "text-green-600"
    case "json":
      return "text-amber-600"
    case "png":
      return "text-purple-600"
    case "py":
      return "text-blue-600"
    default:
      return "text-muted-foreground"
  }
}

export function FilesPage() {
  const [files, setFiles] = useState<GeneratedFile[]>(initialFiles)
  const [searchQuery, setSearchQuery] = useState("")
  const [viewMode, setViewMode] = useState<"grid" | "list">("list")
  const [selectedFiles, setSelectedFiles] = useState<Set<string>>(new Set())

  const filteredFiles = files.filter((file) => file.name.toLowerCase().includes(searchQuery.toLowerCase()))

  const deleteFile = (id: string) => {
    setFiles(files.filter((f) => f.id !== id))
    setSelectedFiles((prev) => {
      const next = new Set(prev)
      next.delete(id)
      return next
    })
  }

  const toggleFileSelection = (id: string) => {
    setSelectedFiles((prev) => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }

  return (
    <main className="flex-1 flex flex-col bg-background overflow-hidden">
      {/* Header */}
      <header className="h-14 border-b border-border flex items-center justify-between px-6 bg-card">
        <div className="flex items-center gap-3">
          <h1 className="font-semibold text-foreground">Files</h1>
          <span className="text-sm text-muted-foreground">{files.length} files generated by AI</span>
        </div>
        <div className="flex items-center gap-2">
          {selectedFiles.size > 0 && (
            <Button variant="outline" size="sm" className="gap-2 bg-transparent">
              <Download className="w-4 h-4" />
              Download ({selectedFiles.size})
            </Button>
          )}
        </div>
      </header>

      {/* Toolbar */}
      <div className="h-12 border-b border-border flex items-center justify-between px-6 bg-muted/30">
        <div className="relative w-64">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            type="text"
            placeholder="Search files..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-9 h-8 bg-background"
          />
        </div>
        <div className="flex items-center gap-1 bg-muted rounded-lg p-1">
          <Button
            variant={viewMode === "list" ? "secondary" : "ghost"}
            size="icon"
            className="w-7 h-7"
            onClick={() => setViewMode("list")}
          >
            <List className="w-4 h-4" />
          </Button>
          <Button
            variant={viewMode === "grid" ? "secondary" : "ghost"}
            size="icon"
            className="w-7 h-7"
            onClick={() => setViewMode("grid")}
          >
            <Grid className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Files List */}
      <div className="flex-1 overflow-y-auto p-6">
        {viewMode === "list" ? (
          <div className="space-y-2">
            {/* Table Header */}
            <div className="grid grid-cols-12 gap-4 px-4 py-2 text-xs font-medium text-muted-foreground uppercase tracking-wider">
              <div className="col-span-5">Name</div>
              <div className="col-span-2">Size</div>
              <div className="col-span-3">Generated By</div>
              <div className="col-span-2">Date</div>
            </div>

            {/* File Rows */}
            {filteredFiles.map((file) => {
              const Icon = getFileIcon(file.type)
              return (
                <div
                  key={file.id}
                  onClick={() => toggleFileSelection(file.id)}
                  className={cn(
                    "grid grid-cols-12 gap-4 px-4 py-3 rounded-lg cursor-pointer transition-all duration-200",
                    selectedFiles.has(file.id)
                      ? "bg-primary/10 border border-primary/20"
                      : "bg-card border border-border hover:bg-muted/50",
                  )}
                >
                  <div className="col-span-5 flex items-center gap-3">
                    <Icon className={cn("w-5 h-5", getFileColor(file.type))} />
                    <span className="font-medium text-sm text-foreground truncate">{file.name}</span>
                  </div>
                  <div className="col-span-2 flex items-center text-sm text-muted-foreground">{file.size}</div>
                  <div className="col-span-3 flex items-center gap-2 text-sm text-muted-foreground">
                    <Bot className="w-4 h-4 text-primary" />
                    <span className="truncate">{file.generatedBy}</span>
                  </div>
                  <div className="col-span-2 flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">{file.createdAt}</span>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon" className="w-7 h-7" onClick={(e) => e.stopPropagation()}>
                          <MoreVertical className="w-4 h-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem>
                          <Eye className="w-4 h-4 mr-2" />
                          Preview
                        </DropdownMenuItem>
                        <DropdownMenuItem>
                          <Download className="w-4 h-4 mr-2" />
                          Download
                        </DropdownMenuItem>
                        <DropdownMenuItem className="text-destructive" onClick={() => deleteFile(file.id)}>
                          <Trash2 className="w-4 h-4 mr-2" />
                          Delete
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                </div>
              )
            })}
          </div>
        ) : (
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
            {filteredFiles.map((file) => {
              const Icon = getFileIcon(file.type)
              return (
                <div
                  key={file.id}
                  onClick={() => toggleFileSelection(file.id)}
                  className={cn(
                    "p-4 rounded-lg cursor-pointer transition-all duration-200 border",
                    selectedFiles.has(file.id)
                      ? "bg-primary/10 border-primary/20"
                      : "bg-card border-border hover:bg-muted/50",
                  )}
                >
                  <div className="flex items-start justify-between mb-3">
                    <div className={cn("w-10 h-10 rounded-lg flex items-center justify-center bg-muted")}>
                      <Icon className={cn("w-5 h-5", getFileColor(file.type))} />
                    </div>
                    <DropdownMenu>
                      <DropdownMenuTrigger asChild>
                        <Button variant="ghost" size="icon" className="w-7 h-7" onClick={(e) => e.stopPropagation()}>
                          <MoreVertical className="w-4 h-4" />
                        </Button>
                      </DropdownMenuTrigger>
                      <DropdownMenuContent align="end">
                        <DropdownMenuItem>
                          <Eye className="w-4 h-4 mr-2" />
                          Preview
                        </DropdownMenuItem>
                        <DropdownMenuItem>
                          <Download className="w-4 h-4 mr-2" />
                          Download
                        </DropdownMenuItem>
                        <DropdownMenuItem className="text-destructive" onClick={() => deleteFile(file.id)}>
                          <Trash2 className="w-4 h-4 mr-2" />
                          Delete
                        </DropdownMenuItem>
                      </DropdownMenuContent>
                    </DropdownMenu>
                  </div>
                  <h3 className="font-medium text-sm text-foreground truncate mb-1">{file.name}</h3>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <span>{file.size}</span>
                    <span>•</span>
                    <span>{file.createdAt.split(" ")[0]}</span>
                  </div>
                  <div className="flex items-center gap-1.5 mt-2 text-xs text-muted-foreground">
                    <Bot className="w-3.5 h-3.5 text-primary" />
                    <span className="truncate">{file.generatedBy}</span>
                  </div>
                </div>
              )
            })}
          </div>
        )}

        {filteredFiles.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center mb-4">
              <FileText className="w-8 h-8 text-muted-foreground" />
            </div>
            <h3 className="font-medium text-foreground mb-1">No files found</h3>
            <p className="text-sm text-muted-foreground">Files generated by AI agents will appear here.</p>
          </div>
        )}
      </div>
    </main>
  )
}
